### ISSUE TITLE
It converts &amp; in &

### ISSUE THREAD

**Issue by michelem09** [StevenLooman/saxpath#12]
Hello, 
I have an element like this:

    <someElement>example&amp;example</someElement>

The parsed data with saxpath is: 

    <someElement>example&example</someElement>

This breaks my next process that's a conversion to JS object of the element with https://github.com/Leonidas-from-XIV/node-xml2js 
Any advice how to handle this?

**Comment by michelem09** [comment]
mmm, I think I did it with a custom recorder which inject every text elements into a `<![CDATA[ ]]>` tag.

So now I have the saxptah output like this:

    <someElement><![CDATA[example&example]]></someElement>

And xml2js can handle it fine.

**Comment by StevenLooman** [comment]
Thank you for the issue. Great that you can work around it.

Still, it is a bug. When I have the time (probably not in the near future) I'll have a look at it.

**Comment by StevenLooman** [comment]
I think this is due to the sax parser. It escapes the incoming data for you. It seems that others have troubles with this as well. For example, see https://github.com/isaacs/sax-js/pull/141

Another possible workaround is to change the sax.ENTITIES table before parsing. An example is as follows:
```
sax.ENTITIES.amp = '&amp;';
sax.ENTITIES.gt = '&gt;';
sax.ENTITIES.lt = '&lt;';
```

This then outputs `&amp;` whenever it parses `&amp;`
